site_url <- Sys.getenv("OBS_SITE_URL")
if (!nzchar(site_url)) site_url <- "http://localhost:7788"
site_root <- paste0(sub("/+$", "", site_url), "/")
site_metodologia <- paste0(site_root, "metodologia/")
site_quienes_somos <- paste0(site_root, "quienes-somos.html")

ui <- page_navbar(
  id    = "nav_principal",
  # SIN fillable: el perfil es una página que SCROLLEA. Con fillable (default de
  # bslib) el contenido se comprime para caber en la altura de la ventana y los
  # gráficos colapsan a franjas ilegibles en pantallas normales.
  fillable = FALSE,
  selected = "perfil",
  title = tags$a(
    href = site_root,
    target = "_top",
    title = "Ir al sitio",
    tags$img(src = "assets/brand/observatorio-logo.svg", alt = txt$app_title, height = "32", width = "32")
  ),
  theme = bs_theme(
    version      = 5,
    bg           = paleta$fondo,
    fg           = paleta$texto,
    primary      = paleta$primario,
    secondary    = paleta$secundario,
    base_font    = font_google("Inter"),
    heading_font = font_google("Space Grotesk")
  ),
  header = tags$head(
    # Favicon inline (SVG data-URI): mata el 404 y marca la pestaña con el cobre
    tags$link(
      rel  = "icon",
      type = "image/svg+xml",
      href = paste0(
        "data:image/svg+xml,",
        utils::URLencode(glue(
          '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">',
          '<rect width="32" height="32" rx="6" fill="{paleta$texto}"/>',
          '<path d="M6 24 L13 10 L18 19 L22 13 L26 24 Z" fill="{paleta$primario}"/>',
          '<path d="M13 10 L18 19 L22 13" fill="none" stroke="{paleta$acento_claro}" stroke-width="1.2" stroke-linejoin="round" stroke-linecap="round"/>',
          '<path d="M6 24h20" stroke="{paleta$acento_claro}" stroke-width="1.5"/>',
          "</svg>"
        ), reserved = TRUE)
      )
    ),
    # Cuando la app vive dentro del sitio Quarto, la navegación superior la
    # aporta el sitio. La app independiente conserva su navbar completa.
    tags$script(HTML('
      (() => {
        const embedded = new URLSearchParams(window.location.search).get("embed") === "1";
        if (embedded) document.documentElement.classList.add("obs-embedded");
      })();
    ')),
    # La pestaña se puede abrir desde Quarto mediante ?tab=...; el clic
    # ocurre cuando Shiny ya terminó de enlazar sus controles.
    tags$script(HTML('
      $(document).on("shiny:connected", function() {
        const tab = new URLSearchParams(window.location.search).get("tab");
        if (!["perfil", "comparador"].includes(tab)) return;
        const link = document.querySelector(`#nav_principal a[data-value="${tab}"]`);
        if (link) link.click();
      });
    ')),
    tags$style(HTML(
      "html.obs-embedded .bslib-page-navbar > .navbar {",
      "  display: none !important;",
      "}",
      "html.obs-embedded .bslib-page-navbar {",
      "  padding-top: 0 !important;",
      "}",
      ".bslib-page-navbar > .navbar {",
      "  position: sticky;",
      "  top: 0;",
      "  z-index: 1030;",
      "  flex-shrink: 0;",
      "  min-height: 52px;",
      "  background-color: #2D2018 !important;",
      "  color: #F5F0E8;",
      "  border: 0;",
      "  border-bottom: 1px solid rgba(245, 240, 232, 0.1);",
      "  box-shadow: none !important;",
      "  font-family: 'Space Grotesk', sans-serif;",
      "}",
      ".bslib-page-navbar > .navbar .navbar-brand {",
      "  flex-shrink: 0;",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-size: 0.96rem;",
      "  font-weight: 600;",
      "  letter-spacing: -0.015em;",
      "}",
      ".bslib-page-navbar > .navbar .navbar-collapse {",
      "  justify-content: flex-end;",
      "}",
      ".bslib-page-navbar > .navbar #nav_principal {",
      "  margin-left: auto;",
      "}",
      "@media (min-width: 768px) {",
      "  .bslib-page-navbar > .navbar > .container-fluid {",
      "    display: flex !important;",
      "    align-items: center;",
      "  }",
      "  .bslib-page-navbar > .navbar .navbar-header {",
      "    float: none !important;",
      "  }",
      "  .bslib-page-navbar > .navbar .navbar-collapse.collapse {",
      "    display: flex !important;",
      "    flex: 1 1 auto;",
      "    align-items: center;",
      "    width: auto !important;",
      "    position: static !important;",
      "  }",
      "  .bslib-page-navbar > .navbar > .container-fluid {",
      "    position: relative;",
      "  }",
      "  .bslib-page-navbar > .navbar #nav_principal {",
      "    position: absolute;",
      "    top: 0;",
      "    right: 0.75rem;",
      "    display: flex;",
      "    float: none !important;",
      "    margin-left: auto !important;",
      "  }",
      "}",
      ".bslib-page-navbar > .navbar .navbar-nav > .nav-item > a,",
      ".bslib-page-navbar > .navbar .navbar-nav > .bslib-nav-item > a {",
      "  position: relative;",
      "  display: flex;",
      "  min-height: 52px;",
      "  align-items: center;",
      "  padding: 0 0.85rem !important;",
      "  color: rgba(245, 240, 232, 0.72) !important;",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-size: 0.8rem;",
      "  font-weight: 500;",
      "  letter-spacing: 0.01em;",
      "}",
      ".bslib-page-navbar > .navbar .navbar-nav > .nav-item > a:hover,",
      ".bslib-page-navbar > .navbar .navbar-nav > .nav-item > a:focus,",
      ".bslib-page-navbar > .navbar .navbar-nav > .bslib-nav-item > a:hover,",
      ".bslib-page-navbar > .navbar .navbar-nav > .bslib-nav-item > a:focus,",
      ".bslib-page-navbar > .navbar .navbar-nav .nav-link.active {",
      "  color: #F5F0E8 !important;",
      "}",
      ".bslib-page-navbar > .navbar .navbar-nav .nav-link.active::after {",
      "  position: absolute;",
      "  right: 0.85rem;",
      "  bottom: 0;",
      "  left: 0.85rem;",
      "  height: 2px;",
      "  content: '';",
      "  background: #BC5F33;",
      "}"
    )),
    tags$style(HTML(glue(
      "@import url('https://fonts.googleapis.com/css2?",
      "family=Space+Grotesk:wght@500;600;700",
      "&family=Inter:wght@400;500;600",
      "&family=IBM+Plex+Mono:wght@400;500",
      "&family=Space+Grotesk:wght@400;500;600",
      "&family=Space+Grotesk:wght@400;500",
      "&display=swap');",

      ".kpi-valor {{",
      "  font-family: '{tipografia$roles$kpi$familia}';",
      "  font-weight: {tipografia$roles$kpi$peso};",
      "  font-size: {tipografia$roles$kpi$tamaño};",
      "  letter-spacing: {tipografia$roles$kpi$tracking};",
      "  color: {paleta$primario};",
      "  line-height: 1;",
      "}}",

      ".kpi-etiqueta {{",
      "  font-family: '{tipografia$roles$etiqueta$familia}';",
      "  font-size: {tipografia$roles$etiqueta$tamaño};",
      "  letter-spacing: 0.08em;",
      "  text-transform: uppercase;",
      "  color: {paleta$tinta_suave};",
      "  margin-top: 0.3rem;",
      "}}",

      # Chip de variación interanual (▲/▼ + pp) - glifo + número, nunca solo color
      ".kpi-delta {{",
      "  display: inline-block;",
      "  font-family: 'IBM Plex Mono', monospace;",
      "  font-size: 0.85rem;",
      "  padding: 0.1rem 0.6rem;",
      "  border-radius: 999px;",
      "  border: 1px solid {paleta$tinta_suave};",
      "  color: {paleta$texto};",
      "  margin: 0 0.25rem;",
      "}}",

      # Portada editorial: una sola composición, sin cards de Bootstrap ni tabla
      # clara sobre la fotografía. El fondo conserva contexto sin competir con el texto.
      ".perfil-portada {{",
      "  --hero-cobre: {paleta$primario};",
      "  position: relative;",
      "  isolation: isolate;",
      "  display: grid;",
      "  grid-template-rows: minmax(460px, 1fr) auto;",
      "  min-height: 620px;",
      "  overflow: hidden;",
      "  margin-bottom: 1.75rem;",
      "  color: {paleta$fondo};",
      "  background-color: #211d18;",
      "  background-image:",
      "    linear-gradient(90deg, rgba(25, 22, 18, 0.96) 0%, rgba(31, 27, 22, 0.88) 47%, rgba(31, 27, 22, 0.53) 100%),",
      "    url('assets/empresas/mineria-planta-concentradora.png');",
      "  background-position: center 46%;",
      "  background-size: cover;",
      "}}",
      ".perfil-portada::before {{",
      "  content: '';",
      "  position: absolute;",
      "  inset: 0;",
      "  z-index: -1;",
      "  pointer-events: none;",
      "  background: linear-gradient(180deg, rgba(0, 0, 0, 0.08), transparent 42%, rgba(0, 0, 0, 0.28));",
      "}}",
      ".perfil-ficha {{",
      "  display: flex;",
      "  align-items: center;",
      "  min-width: 0;",
      "  padding: clamp(2.75rem, 5vw, 5rem) clamp(2rem, 5vw, 5.25rem);",
      "}}",
      ".perfil-identidad {{",
      "  display: grid;",
      "  grid-template-columns: minmax(0, 1.35fr) minmax(300px, 0.65fr);",
      "  align-items: center;",
      "  gap: clamp(2.5rem, 6vw, 6.5rem);",
      "  width: 100%;",
      "}}",
      ".hero-copy {{ min-width: 0; max-width: 720px; }}",
      ".comparador-vacio {{ border-left: 3px solid #BC5F33; padding: 1rem; color: #5C5240; }}",
      ".hero-nombre {{",
      "  margin: 0;",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-size: clamp(4rem, 7.2vw, 7rem);",
      "  font-weight: 600;",
      "  letter-spacing: -0.055em;",
      "  line-height: 0.92;",
      "  color: {paleta$fondo};",
      "}}",
      ".hero-razon {{",
      "  margin-top: 1.1rem;",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-size: clamp(0.95rem, 1.3vw, 1.15rem);",
      "  font-weight: 500;",
      "  color: {paleta$acento_claro};",
      "}}",
      ".badge-datos {{",
      "  font-family: 'IBM Plex Mono', monospace;",
      "  font-size: 0.75rem;",
      "  color: {paleta$texto};",
      "  background: {paleta$acento_claro};",
      "  border-radius: 4px;",
      "  padding: 0.15rem 0.6rem;",
      "}}",
      ".hero-editorial {{",
      "  max-width: 650px;",
      "  margin: 1.5rem 0 0;",
      "  padding-left: 0;",
      "  border-left: 0;",
      "  font-size: clamp(0.95rem, 1.15vw, 1.08rem);",
      "  line-height: 1.65;",
      "  color: rgba(245, 240, 232, 0.86);",
      "}}",
      ".hero-dossier {{",
      "  padding: 0 0 1rem 1rem;",
      "  border: 0;",
      "  background: transparent;",
      "}}",
      ".hero-meta-grid {{",
      "  display: grid;",
      "  grid-template-columns: repeat(2, minmax(0, 1fr));",
      "  gap: 1.7rem 2.25rem;",
      "}}",
      ".hero-dossier .ficha-campo {{",
      "  min-width: 0;",
      "  margin: 0;",
      "  padding-top: 0;",
      "  border-top: 0;",
      "}}",
      ".ficha-label {{",
      "  font-size: 0.64rem;",
      "  text-transform: uppercase;",
      "  letter-spacing: 0.12em;",
      "  color: rgba(212, 184, 154, 0.78);",
      "}}",
      ".ficha-valor {{",
      "  margin-top: 0.35rem;",
      "  font-size: 0.96rem;",
      "  font-weight: 500;",
      "  line-height: 1.35;",
      "  color: {paleta$fondo};",
      "}}",
      ".hero-propiedad {{",
      "  margin-top: 2rem;",
      "  padding-top: 0;",
      "  border-top: 0;",
      "}}",
      ".hero-propiedad-titulo {{",
      "  margin-bottom: 0.55rem;",
      "  font-size: 0.68rem;",
      "  letter-spacing: 0.09em;",
      "  text-transform: uppercase;",
      "  color: {paleta$acento_claro};",
      "}}",
      ".hero-propietario {{",
      "  display: flex;",
      "  justify-content: space-between;",
      "  gap: 1rem;",
      "  padding: 0.18rem 0;",
      "  font-size: 0.78rem;",
      "  line-height: 1.3;",
      "}}",
      ".hero-propietario-detalle {{",
      "  flex: 0 0 auto;",
      "  color: {paleta$acento_claro};",
      "  font-family: 'IBM Plex Mono', monospace;",
      "  font-size: 0.7rem;",
      "}}",

      # Zócalo de indicadores integrado a la portada.
      ".hero-kpis {{",
      "  display: grid;",
      "  grid-template-columns: repeat(3, minmax(0, 1fr));",
      "  padding: 0 clamp(1rem, 4vw, 4rem);",
      "  background: transparent;",
      "}}",
      ".hero-kpi {{",
      "  position: relative;",
      "  min-width: 0;",
      "  padding: 1.35rem clamp(1rem, 2.5vw, 2.5rem);",
      "}}",
      ".hero-kpi + .hero-kpi {{ border-left: 1px solid rgba(212, 184, 154, 0.16); }}",
      ".hero-kpi .kpi-etiqueta {{ margin: 0 0 0.55rem; color: {paleta$acento_claro}; }}",
      ".hero-kpi .kpi-valor {{",
      "  white-space: nowrap;",
      "  font-family: 'IBM Plex Mono', monospace;",
      "  font-size: clamp(1.6rem, 2.45vw, 2.6rem);",
      "  font-weight: 500;",
      "  letter-spacing: -0.05em;",
      "  color: {paleta$fondo};",
      "}}",
      ".hero-kpi-contexto {{",
      "  min-height: 1.35rem;",
      "  margin-top: 0.6rem;",
      "  font-size: 0.72rem;",
      "  line-height: 1.35;",
      "  color: rgba(245, 240, 232, 0.62);",
      "}}",
      ".hero-kpi .kpi-delta {{",
      "  margin: 0 0.18rem 0 0;",
      "  padding: 0.08rem 0.45rem;",
      "  border-color: rgba(212, 184, 154, 0.55);",
      "  color: {paleta$fondo};",
      "  font-size: 0.7rem;",
      "}}",
      "@media (max-width: 991.98px) {{",
      "  .perfil-portada {{ grid-template-rows: auto auto; min-height: 0; background-position: 58% center; }}",
      "  .perfil-identidad {{ grid-template-columns: 1fr; gap: 2.5rem; }}",
      "  .hero-copy {{ max-width: 680px; }}",
      "  .hero-dossier {{ max-width: 680px; }}",
      "}}",
      "@media (max-width: 680px) {{",
      "  .perfil-portada {{ background-position: 64% center; }}",
      "  .perfil-ficha {{ padding: 2.5rem 1.25rem; }}",
      "  .hero-nombre {{ font-size: clamp(3.25rem, 18vw, 5rem); }}",
      "  .hero-editorial {{ margin-top: 1.5rem; font-size: 0.92rem; }}",
      "  .hero-dossier {{ padding: 1.2rem; }}",
      "  .hero-meta-grid {{ grid-template-columns: 1fr; gap: 0.9rem; }}",
      "  .hero-kpis {{ grid-template-columns: 1fr; padding: 0 1.25rem; }}",
      "  .hero-kpi {{ padding: 1.15rem 0; }}",
      "  .hero-kpi + .hero-kpi {{ border-top: 1px solid rgba(212, 184, 154, 0.22); border-left: 0; }}",
      "  .hero-kpi .kpi-valor {{ font-size: 2rem; }}",
      "}}",

      # Sistema visual de las secciones del perfil.
      ".perfil-seccion {{",
      "  margin: 0;",
      "  padding: clamp(3rem, 5vw, 5rem) clamp(1.25rem, 4vw, 4.5rem);",
      "  border-top: 1px solid rgba(45, 40, 32, 0.10);",
      "}}",
      ".perfil-seccion + .perfil-seccion {{",
      "  background: rgba(255, 255, 255, 0.22);",
      "}}",
      ".section-header {{",
      "  display: flex;",
      "  align-items: baseline;",
      "  gap: 0.9rem;",
      "  margin: 0 0 1.75rem;",
      "  padding: 0;",
      "  border: 0;",
      "}}",
      ".section-number {{",
      "  flex: 0 0 auto;",
      "  color: {paleta$primario};",
      "  font-family: 'IBM Plex Mono', monospace;",
      "  font-size: 0.75rem;",
      "  font-weight: 500;",
      "  letter-spacing: 0.08em;",
      "}}",
      ".section-title {{",
      "  margin: 0;",
      "  color: {paleta$texto};",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-size: clamp(1.8rem, 3vw, 2.7rem);",
      "  font-weight: {tipografia$roles$titulo$peso};",
      "  letter-spacing: -0.035em;",
      "  line-height: 1;",
      "}}",

      # Pendiente declarado: el hueco es contenido (qué falta y por qué)
      ".pendiente {{",
      "  background: rgba(156, 112, 16, 0.07);",
      "  border-left: 4px solid {paleta$datos[[3]]};",
      "  border-radius: 0.35rem;",
      "  padding: 1.1rem 1.3rem;",
      "  font-size: 0.92rem;",
      "  line-height: 1.6;",
      "  color: {paleta$tinta_suave};",
      "}}",
      ".pendiente-titulo {{",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-weight: {tipografia$roles$titulo$peso};",
      "  color: {paleta$texto};",
      "  margin-bottom: 0.4rem;",
      "}}",

      ".tabla-propiedad {{ font-size: 0.92rem; }}",

      # Tarjetas: la unidad vive en el encabezado, no escondida en el título.
      ".perfil-seccion .card {{",
      "  height: 100%;",
      "  border: 1px solid rgba(45, 40, 32, 0.12);",
      "  border-radius: 0.2rem;",
      "  background: rgba(255, 255, 255, 0.58);",
      "  box-shadow: 0 8px 24px rgba(45, 40, 32, 0.035);",
      "}}",
      ".perfil-seccion .card .card-header {{",
      "  display: flex;",
      "  align-items: center;",
      "  min-height: 3.65rem;",
      "  padding: 0.95rem 1.1rem;",
      "  background: transparent;",
      "  border-bottom: 1px solid rgba(45, 40, 32, 0.10);",
      "}}",
      ".panel-header {{",
      "  display: flex;",
      "  align-items: baseline;",
      "  justify-content: space-between;",
      "  gap: 1rem;",
      "  width: 100%;",
      "}}",
      ".panel-title {{",
      "  color: {paleta$texto};",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-size: 0.98rem;",
      "  font-weight: {tipografia$roles$titulo$peso};",
      "  letter-spacing: {tipografia$roles$titulo$tracking};",
      "  line-height: 1.25;",
      "}}",
      ".panel-unit {{",
      "  flex: 0 0 auto;",
      "  color: {paleta$tinta_suave};",
      "  font-family: 'IBM Plex Mono', monospace;",
      "  font-size: 0.66rem;",
      "  font-weight: 500;",
      "  letter-spacing: 0.06em;",
      "  text-transform: uppercase;",
      "  white-space: nowrap;",
      "}}",
      ".perfil-seccion .card-body {{ padding: 0.65rem 1.1rem 1.1rem; }}",
      ".perfil-seccion .card .card-footer {{",
      "  padding: 0.7rem 1.1rem;",
      "  background: transparent;",
      "  border-top: 1px dashed rgba(45, 40, 32, 0.15);",
      "  color: {paleta$tinta_suave};",
      "}}",
      ".perfil-seccion .card .card-footer small {{",
      "  color: {paleta$tinta_suave};",
      "  font-size: 0.68rem;",
      "  line-height: 1.45;",
      "  text-transform: none;",
      "  letter-spacing: 0.02em;",
      "}}",

      # Landing
      ".landing-panel {{",
      "  background-color: {paleta$texto};",
      "  min-height: calc(100vh - 56px);",
      "  display: flex;",
      "  flex-direction: column;",
      "  justify-content: center;",
      "  padding: 2rem 6rem;",
      "}}",
      ".landing-supertitulo {{",
      "  font-family: '{tipografia$roles$pestaña$familia}';",
      "  font-size: {tipografia$roles$etiqueta$tamaño};",
      "  letter-spacing: 0.15em;",
      "  text-transform: uppercase;",
      "  color: {paleta$acento_claro};",
      "  margin-bottom: 1.5rem;",
      "}}",
      ".landing-titulo {{",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-weight: 500;",
      "  font-size: 4.5rem;",
      "  line-height: 1.2;",
      "  color: {paleta$fondo};",
      "  margin-bottom: 0;",
      "  max-width: 700px;",
      "}}",
      ".landing-acento {{",
      "  color: {paleta$primario};",
      "}}",
      ".landing-subtitulo {{",
      "  font-family: '{tipografia$roles$texto$familia}';",
      "  font-size: 1.4rem;",
      "  color: #b8a898;",
      "  max-width: 560px;",
      "  margin-top: 1.5rem;",
      "  line-height: 1.6;",
      "}}",
      ".landing-boton {{",
      "  margin-top: 2.5rem;",
      "  padding: 0.75rem 2rem;",
      "  background: transparent;",
      "  color: {paleta$fondo};",
      "  border: 1px solid {paleta$fondo};",
      "  border-radius: 0.4rem;",
      "  font-family: '{tipografia$roles$subtitulo$familia}';",
      "  font-size: 0.95rem;",
      "  font-weight: 500;",
      "  width: fit-content;",
      "  cursor: pointer;",
      "  transition: background 0.2s, color 0.2s;",
      "}}",
      ".landing-boton:hover {{",
      "  background: {paleta$fondo};",
      "  color: {paleta$texto};",
      "}}",
      ".navbar-nav .nav-link {{",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-weight: 500;",
      "  font-size: 0.9rem;",
      "}}",

      # Logo clickeable: es el único elemento de Inicio.
      ".navbar-brand a {{ text-decoration: none; display: inline-flex; align-items: center; }}",

      # Rótulo de agrupación dentro de una sección.
      ".sub-header {{",
      "  font-family: 'Space Grotesk', sans-serif;",
      "  font-weight: 600;",
      "  font-size: 0.72rem;",
      "  letter-spacing: 0.12em;",
      "  text-transform: uppercase;",
      "  color: {paleta$texto};",
      "  border-left: 2px solid {paleta$secundario};",
      "  padding-left: 0.7rem;",
      "  margin: 2rem 0 0.85rem;",
      "}}",
      ".perfil-seccion .bslib-grid, .perfil-seccion .row {{ row-gap: 1rem; }}",
      ".perfil-seccion-chat {{ background: {paleta$texto}; color: {paleta$fondo}; }}",
      ".perfil-seccion-chat .section-title {{ color: {paleta$fondo}; }}",
      ".chat-intro {{ max-width: 700px; margin: -0.5rem 0 1.5rem; }}",
      ".chat-kicker {{",
      "  display: block;",
      "  margin-bottom: 0.45rem;",
      "  color: {paleta$acento_claro};",
      "  font-family: 'IBM Plex Mono', monospace;",
      "  font-size: 0.68rem;",
      "  letter-spacing: 0.12em;",
      "  text-transform: uppercase;",
      "}}",
      ".chat-intro p {{",
      "  margin: 0;",
      "  color: rgba(245, 240, 232, 0.72);",
      "  font-size: 0.95rem;",
      "  line-height: 1.5;",
      "}}",
      ".chat-shell {{",
      "  min-height: 420px;",
      "  padding: 1rem;",
      "  border: 1px solid rgba(212, 184, 154, 0.24);",
      "  background: rgba(245, 240, 232, 0.06);",
      "}}",
      ".chat-shell .card {{",
      "  border: 0;",
      "  background: transparent;",
      "  box-shadow: none;",
      "  color: {paleta$fondo};",
      "}}",
      "@media (max-width: 680px) {{",
      "  .perfil-seccion {{ padding: 2.75rem 1.1rem; }}",
      "  .section-header {{ gap: 0.65rem; margin-bottom: 1.25rem; }}",
      "  .section-title {{ font-size: 2rem; }}",
      "  .panel-header {{ align-items: flex-start; flex-direction: column; gap: 0.3rem; }}",
      "  .panel-unit {{ white-space: normal; }}",
      "  .chat-shell {{ padding: 0.5rem; }}",
      "  .bslib-page-navbar > .navbar .navbar-nav > .nav-item > a,",
      "  .bslib-page-navbar > .navbar .navbar-nav > .bslib-nav-item > a {{",
      "    min-height: 42px;",
      "    padding: 0 0.25rem !important;",
      "  }}",
      "}}"
    )))
  ),


  # ── Perfil por empresa (módulos curados; docs/perfil_esquema.md §6) ───────
  nav_panel(
    value = "perfil",
    title = txt$nav$perfil,

    layout_columns(
      col_widths = c(3, 9),
      selectInput("sel_empresa", txt$perfil$empresa, choices = choices_empresa),
      NULL
    ),

    mod_hero_ui("hero"),
    mod_sec01_ui("sec01"),
    mod_sec02_ui("sec02"),
    mod_sec03_ui("sec03"),
    mod_sec04_ui("sec04"),
    mod_chat_documental_ui("chat")
  ),

  nav_panel(
    value = "comparador",
    title = txt$nav$comparacion,
    card(
      card_header("Comparador"),
      card_body(
        p("Selecciona empresas para contrastar sus indicadores financieros y productivos."),
        div(class = "comparador-vacio", "Módulo en construcción")
      )
    )
  ),

  nav_item(a("Metodología", href = site_metodologia, target = "_top")),
  nav_item(a("Quiénes somos", href = site_quienes_somos, target = "_top"))
)
